---
abstract: 'Experimental 4th generation Win32 Perl distribution builder'
author:
  - 'Curtis Jewell <csjewell@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::More: 0.47
  Test::Output: 0.11
  Test::UseAllModules: 0.09
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist::WiX
name: Perl-Dist-WiX
no_index:
  directory:
    - inc
    - share
    - t
recommends:
  Readonly::XS: 1.05
requires:
  Alien::WiX: v0.300000
  Data::UUID: 1.149
  Exception::Class: 1.22
  File::ShareDir: 1.00
  List::MoreUtils: 0.07
  Module::CoreList: 2.17
  Object::InsideOut: 3.53
  Perl::Dist: 1.12
  Readonly: 1.03
  Win32: 0.35
  perl: 5.6.0
  version: 0.76
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Perl-Dist-WiX
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Perl-Dist-WiX
version: 0.160000
