---
abstract: 'Experimental 4th generation Win32 Perl distribution builder'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist::WiX
name: Perl-Dist-WiX
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  File::ShareDir: 1.00
  Moose: 0.58
  Perl::Dist: 1.04
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_01
