---
abstract: '4th generation Win32 Perl distribution builder'
author:
  - 'Curtis Jewell <csjewell@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
  Test::Output: 0.11
  Test::Perl::Dist: 0.200
  Test::UseAllModules: 0.09
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist::WiX
name: Perl-Dist-WiX
no_index:
  directory:
    - inc
    - share
    - t
recommends:
  Readonly::XS: 1.05
requires:
  Alien::WiX: 0.300000
  CPAN: 1.9450
  Data::Dump::Streamer: 2.08
  Data::UUID: 1.149
  Devel::StackTrace: 1.20
  Exception::Class: 1.22
  File::Copy::Recursive: 0.38
  File::List::Object: 0.189
  File::PathList: 1.04
  File::ShareDir: 1.00
  IO::Capture: 0.05
  IO::String: 1.08
  List::MoreUtils: 0.07
  Module::CoreList: 2.18
  Moose: 0.88
  Object::Tiny: 1.06
  Process: 0.26
  Readonly: 1.03
  Template: 2.22
  URI: 1.35
  WiX3: 0.006
  Win32: 0.35
  Win32::Exe: 0.11
  Win32API::File: 0.1001
  parent: 0.221
  perl: 5.8.1
resources:
  DLSIP: http://search.cpan.org/dlsip?RpdOp
  IRC: irc://irc.perl.org/#win32
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Perl-Dist-WiX
  homepage: http://csjewell.comyr.com/perl/
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Perl-Dist-WiX/
version: 1.090_102
